server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: LTAI5t7roahcC4pWuvUHWfEU
    keySecret: KMCdv12GToJXbYDGWcHgJg2ceJCxpo
    bucketName: wjl-srb